# -*- coding: utf-8 -*-
"""TopicModeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1_h7R-CfYiJK0K5KMerIdk__HWiGh08
"""

from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

pip install bertopic

model = BERTopic(language="english")
topics, probs = model.fit_transform(docs)

model.get_topic_freq().head()

model.get_topic(49)[:10]